### ISSUE TITLE
Step 8: MLST - run disconnecting  

### ISSUE THREAD

**Issue by Drojok** [JoseBarbero/CamPype#136]
Hi Jose, 
I need your support and guidance. 
I am running CamPype (43 isolates of _C. coli_) but it is stopping at step 8. I have provided part of the long message provided during the failure.

Step 8: MLST                                                                      *
*                                                                                   *
*************************************************************************************
[13:38:58] Checking mlst dependencies:
[13:38:58] Found 'blastn' => /home/sequser/miniconda3/envs/campype/bin/blastn
[13:38:58] Found 'any2fasta' => /home/sequser/miniconda3/envs/campype/bin/any2fasta
[13:38:58] Found blastn: 2.9.0+
[13:38:58] Excluding 2 schemes: abaumannii ecoli_2

Warning: [blastn] Number of threads was reduced to 20 to match the number of available CPUs
[13:38:58] Found exact allele match campylobacter.glnA-39
[13:38:58] Found exact allele match campylobacter.uncA-17
[13:38:58] Found exact allele match campylobacter.gltA-30
[13:38:58] Found exact allele match campylobacter.pgm-104
[13:38:58] Found exact allele match campylobacter.aspA-33
[13:38:58] Found exact allele match campylobacter.tkt-206
[13:38:58] Found exact allele match campylobacter.glyA-79

Warning: [blastn] Number of threads was reduced to 20 to match the number of available CPUs

This is repeated several times and then on the last line it ends with "unable to read from" - as below 

Warning: [blastn] Number of threads was reduced to 20 to match the number of available CPUs
[13:39:16] Found exact allele match campylobacter.glnA-66
[13:39:16] Found exact allele match campylobacter.glyA-82
[13:39:16] Found exact allele match campylobacter.pgm-104
[13:39:16] Found exact allele match campylobacter.aspA-33
[13:39:16] Found exact allele match campylobacter.tkt-43
[13:39:16] Found exact allele match campylobacter.uncA-17
[13:39:16] Found exact allele match campylobacter.gltA-30
[13:39:16] Unable to read from ''

it also adds this info and more; 

Traceback (most recent call last):
  File "/home/sequser/miniconda3/envs/campype/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/sequser/miniconda3/envs/campype/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err

OSError: [Errno 113] No route to host

At the end of a ling information, it provides this additional note 
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rest.pubmlst.org', port=80): Max retries exceeded with url: /db/pubmlst_campylobacter_seqdef/schemes/1/profiles_csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74969119ca90>: Failed to establish a new connection: [Errno 113] No route to host'))

I do have good internet connectivity and believe error in connectivity is not due to my internet 

I have no idea what is happening. 
Please assist. 

Thanks
 
David

**Comment by JoseBarbero** [comment]
Hi David

I just tried an example run on a clean machine and it worked fine. Maybe the host for that step was down in that moment?
Could you try again? Maybe they solved the issue already.

Let me know if the issue persists.

Thanks.
Jose.

**Comment by ireneortega** [comment]
Closed due to inactivity of the user
